import { noteEvent, type Song } from "./songTypes";

const n = noteEvent;

// Shepherd's Hey is written as two repeated strains. The B-strain pickup is
// played once before that strain's repeat, so the performed form is A A +
// pickup + B B (not A + pickup + B).
const SHEPHERDS_HEY_A = [
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 0.75),
  n("Fs4", 0.25),
  n("G4", 1),
  n("G4", 1),
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 0.75),
  n("Fs4", 0.25),
  n("E4", 1, { tieToNext: true }),
  n("E4", 1),
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 0.75),
  n("Fs4", 0.25),
  n("G4", 1),
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 1),
  n("A4", 1),
  n("D4", 2),
];

const SHEPHERDS_HEY_B_PICKUP = [n("D4", 0.75), n("E4", 0.25)];

const SHEPHERDS_HEY_B = [
  n("Fs4", 1),
  n("D4", 1),
  n("G4", 1, { tieToNext: true }),
  n("G4", 1),
  n("Fs4", 1),
  n("D4", 1),
  n("E4", 1, { tieToNext: true }),
  n("E4", 1),
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 0.75),
  n("Fs4", 0.25),
  n("G4", 1),
  n("Fs4", 0.75),
  n("G4", 0.25),
  n("A4", 1),
  n("A4", 1),
  n("D4", 2),
];

export const ENGLISH_FOLK_SONGS: Song[] = [
  {
    id: "shepherds-hey",
    title: "Shepherd's Hey",
    difficulty: 1,
    description:
      "Traditional Morris tune. A good F♯ fingering and rhythm workout.",
    playable: true,
    rhythmVerified: true,
    events: [
      ...SHEPHERDS_HEY_A,
      ...SHEPHERDS_HEY_A,
      ...SHEPHERDS_HEY_B_PICKUP,
      ...SHEPHERDS_HEY_B,
      ...SHEPHERDS_HEY_B,
    ],
  },
  {
    id: "over-the-hills",
    title: "Over the Hills and Far Away",
    difficulty: 2,
    description:
      "Recorder version using the calibrated Carry-on fingerings. Pitch sequence is ready; detailed rhythm is not yet verified.",
    playable: true,
    rhythmVerified: false,
    notes: [
      "D4",
      "G4",
      "B4",
      "G4",
      "B4",
      "G4",
      "E4",
      "E4",
      "D4",
      "G4",
      "B4",
      "G4",
      "B4",
      "C5",
      "D5",
      "A4",
      "D4",
      "G4",
      "B4",
      "G4",
      "B4",
      "G4",
      "E4",
      "C5",
      "E4",
      "D4",
      "D4",
      "D4",
      "B4",
      "C5",
      "D5",
      "A4",
      "D5",
      "C5",
      "B4",
      "A4",
      "G4",
      "E4",
      "E4",
      "D5",
      "C5",
      "B4",
      "G4",
      "C5",
      "D5",
      "A4",
      "D5",
      "D5",
      "C5",
      "B4",
      "A4",
      "G4",
      "E4",
      "C5",
      "E4",
      "D4",
      "D4",
      "D4",
      "B4",
      "C5",
      "D5",
      "A4",
    ],
  },
  {
    id: "early-one-morning",
    title: "Early One Morning",
    difficulty: 2,
    description: "Traditional English air.",
    playable: false,
  },
  {
    id: "lincolnshire-poacher",
    title: "The Lincolnshire Poacher",
    difficulty: 2,
    description: "Traditional English song.",
    playable: false,
  },
  {
    id: "country-gardens",
    title: "Country Gardens",
    difficulty: 3,
    description: "Classic English dance melody.",
    playable: false,
  },
  {
    id: "scarborough-fair",
    title: "Scarborough Fair",
    difficulty: 3,
    description: "Traditional modal melody.",
    playable: false,
  },
  {
    id: "greensleeves",
    title: "Greensleeves",
    difficulty: 4,
    description: "Historic English melody.",
    playable: false,
  },
];
